import json, os, random

def rand_id():
    return "%08x" % random.randint(0, 0xFFFFFFFF)

def md(source):
    return {"cell_type": "markdown", "id": rand_id(), "metadata": {}, "source": source}

def code(source):
    return {"cell_type": "code", "id": rand_id(), "metadata": {},
            "source": source, "outputs": [], "execution_count": None}

def L(*lines):
    return "\n".join(lines)

cells = []

# ── CELL 00 ── Title & Overview ──────────────────────────────────────────────
cells.append(md(L(
    "# Python Conditionals — Complete Learning Guide",
    "",
    "Conditionals are the **decision-making engine** of every program.",
    "They let your code ask questions and take different paths based on the answers.",
    "",
    "## What You Will Learn",
    "",
    "| # | Topic | Key Idea |",
    "|---|-------|----------|",
    "| 1 | `if` statement | Execute code only when a condition is True |",
    "| 2 | `if / else` | Choose between two paths |",
    "| 3 | `if / elif / else` | Choose between many paths |",
    "| 4 | Nested conditionals | Conditions inside conditions |",
    "| 5 | Ternary expression | One-line conditional assignment |",
    "| 6 | Truthy & Falsy | How Python evaluates any value as True/False |",
    "| 7 | Comparison operators | ==, !=, <, >, <=, >=, in, is |",
    "| 8 | Logical operators | and, or, not — combining conditions |",
    "| 9 | Short-circuit evaluation | Python stops early when possible |",
    "| 10 | Guard clauses | Cleaner code with early exits |",
    "| 11 | `match` statement | Pattern matching (Python 3.10+) |",
    "| 12 | Practice challenges | 5 real-world exercises with solutions |",
    "",
    "> **How to use this notebook:** Read the explanation in each markdown cell,",
    "> then run the code cell below it. Modify the values and re-run to experiment.",
)))

# ── CELL 01 ── Section 1 header ──────────────────────────────────────────────
cells.append(md(L(
    "---",
    "## 1. The `if` Statement — Execute Only When True",
    "",
    "**Syntax:**",
    "```python",
    "if condition:",
    "    # this block runs ONLY when condition is True",
    "    statement_1",
    "    statement_2",
    "```",
    "",
    "**Rules:**",
    "- The condition must evaluate to `True` or `False`",
    "- The colon `:` at the end of the `if` line is **mandatory**",
    "- The indented block (4 spaces) defines what runs when condition is True",
    "- If the condition is False, the block is **skipped entirely**",
    "",
    "**Flowchart:**",
    "```",
    "         condition",
    "        /         \\",
    "      True       False",
    "       |           |",
    "   run block    skip block",
    "       |           |",
    "       └─────┬─────┘",
    "          continue",
    "```",
)))

cells.append(code(L(
    "# Basic if statement — change the temperature to see different behaviour",
    "temperature = 35",
    "",
    "if temperature > 30:",
    '    print("It\'s hot outside!")',
    '    print("Stay hydrated.")',
    "",
    '# This always runs — it\'s outside the if block (no indentation)',
    'print("Program continues here regardless.")',
)))

# ── CELL 03 ── Real-world if example ─────────────────────────────────────────
cells.append(code(L(
    "# Real-world example: check if a file would be valid to upload",
    "file_size_mb = 4.2",
    "MAX_SIZE_MB  = 5.0",
    "",
    "if file_size_mb <= MAX_SIZE_MB:",
    '    print(f"File size {file_size_mb} MB is within the {MAX_SIZE_MB} MB limit.")',
    '    print("Upload allowed.")',
    "",
    "# What happens when you change file_size_mb to 6.0?",
)))

# ── CELL 04 ── Section 2: if/else ────────────────────────────────────────────
cells.append(md(L(
    "---",
    "## 2. `if / else` — Two-Way Decision",
    "",
    "Use `else` when you want to do something **specific** when the condition is False.",
    "",
    "```python",
    "if condition:",
    "    # runs when True",
    "else:",
    "    # runs when False",
    "```",
    "",
    "> **Note:** `else` never has a condition — it catches everything the `if` missed.",
)))

cells.append(code(L(
    "# Login check",
    "password_entered = 'python123'",
    "correct_password  = 'python123'",
    "",
    "if password_entered == correct_password:",
    '    print("Access granted. Welcome!")',
    "else:",
    '    print("Wrong password. Access denied.")',
)))

cells.append(code(L(
    "# Number classification",
    "number = -7",
    "",
    "if number >= 0:",
    '    print(f"{number} is non-negative")',
    "else:",
    '    print(f"{number} is negative")',
    "",
    "# Try: change number to 0, 5, -1",
)))

# ── CELL 07 ── Section 3: if/elif/else ───────────────────────────────────────
cells.append(md(L(
    "---",
    "## 3. `if / elif / else` — Multi-Way Decision",
    "",
    "`elif` (short for *else if*) lets you check **multiple conditions** in sequence.",
    "Python tests them top-to-bottom and stops at the **first True** one.",
    "",
    "```python",
    "if condition_1:",
    "    # runs if condition_1 is True",
    "elif condition_2:",
    "    # runs if condition_1 is False AND condition_2 is True",
    "elif condition_3:",
    "    # runs if condition_1 and condition_2 are False AND condition_3 is True",
    "else:",
    "    # runs if ALL conditions above are False",
    "```",
    "",
    "**Key point:** Only ONE branch ever runs — the first True one.",
    "Even if multiple conditions are True, Python stops after the first match.",
)))

cells.append(code(L(
    "# Grading system",
    "score = 72",
    "",
    "if score >= 90:",
    '    grade = "A"',
    '    remark = "Excellent"',
    "elif score >= 80:",
    '    grade = "B"',
    '    remark = "Good"',
    "elif score >= 70:",
    '    grade = "C"',
    '    remark = "Average"',
    "elif score >= 60:",
    '    grade = "D"',
    '    remark = "Below average"',
    "else:",
    '    grade = "F"',
    '    remark = "Fail"',
    "",
    'print(f"Score: {score} → Grade: {grade} ({remark})")',
)))

cells.append(code(L(
    "# Time-of-day greeting — only ONE branch runs",
    "hour = 14   # 24-hour clock; try 7, 12, 18, 22",
    "",
    "if hour < 6:",
    '    greeting = "Good night"',
    "elif hour < 12:",
    '    greeting = "Good morning"',
    "elif hour < 17:",
    '    greeting = "Good afternoon"',
    "elif hour < 21:",
    '    greeting = "Good evening"',
    "else:",
    '    greeting = "Good night"',
    "",
    'print(f"Hour {hour:02d}:00 → {greeting}!")',
)))

# ── CELL 10 ── Section 4: Nested conditionals ────────────────────────────────
cells.append(md(L(
    "---",
    "## 4. Nested Conditionals — Conditions Inside Conditions",
    "",
    "You can place an `if` block inside another `if` block.",
    "Each inner `if` only runs when its outer condition is True.",
    "",
    "```python",
    "if outer_condition:",
    "    if inner_condition:",
    "        # runs only when BOTH are True",
    "```",
    "",
    "**When to nest vs when to use `and`:**",
    "",
    "| Situation | Use |",
    "|-----------|-----|",
    "| Both conditions must be True to do the same thing | `and` in one `if` |",
    "| Inner condition only makes sense if outer is True first | nested `if` |",
    "| You need different actions for each combination | nested `if/else` |",
    "",
    "> **Warning:** More than 2 levels of nesting usually signals that your",
    "> code needs to be restructured (see **Guard Clauses** in Section 10).",
)))

cells.append(code(L(
    "# E-commerce checkout: check login, then check cart, then check stock",
    "is_logged_in = True",
    "cart_total    = 85.0",
    "item_in_stock = True",
    "",
    "if is_logged_in:",
    '    print("User is logged in.")',
    "    if cart_total > 0:",
    '        print(f"Cart total: £{cart_total:.2f}")',
    "        if item_in_stock:",
    '            print("Order confirmed!")',
    "        else:",
    '            print("Sorry, item is out of stock.")',
    "    else:",
    '        print("Your cart is empty.")',
    "else:",
    '    print("Please log in to continue.")',
)))

cells.append(code(L(
    "# The same logic rewritten using 'and' — compare readability",
    "is_logged_in  = True",
    "cart_total    = 85.0",
    "item_in_stock = True",
    "",
    "if is_logged_in and cart_total > 0 and item_in_stock:",
    '    print(f"Order confirmed! Cart: £{cart_total:.2f}")',
    "elif not is_logged_in:",
    '    print("Please log in.")',
    "elif cart_total == 0:",
    '    print("Cart is empty.")',
    "else:",
    '    print("Item out of stock.")',
    "",
    '# Which style is easier to read? It depends on whether you need',
    '# separate messages for each failure — then nesting is justified.',
)))

# ── CELL 13 ── Section 5: Ternary ────────────────────────────────────────────
cells.append(md(L(
    "---",
    "## 5. Ternary Expression (Conditional Expression)",
    "",
    "A one-line shorthand for a simple `if/else` that **assigns a value**.",
    "",
    "```python",
    "value = result_if_true  if  condition  else  result_if_false",
    "```",
    "",
    "**When to use:** Only for simple, readable one-liners.",
    "If the condition or values are complex, use a full `if/else` block.",
    "",
    "| Full `if/else` | Ternary equivalent |",
    "|---|---|",
    "| `if x > 0: sign = 'positive'` | `sign = 'positive' if x > 0 else 'non-positive'` |",
    "| `else: sign = 'non-positive'` | *(same as above)* |",
)))

cells.append(code(L(
    "# Simple assignments — perfect for ternary",
    "age = 17",
    "",
    '# Long form',
    "if age >= 18:",
    '    status = "adult"',
    "else:",
    '    status = "minor"',
    'print("Long form:", status)',
    "",
    '# Ternary — same result, one line',
    'status = "adult" if age >= 18 else "minor"',
    'print("Ternary:  ", status)',
)))

cells.append(code(L(
    "# Practical uses of ternary",
    "score     = 65",
    "items     = []",
    "username  = ''",
    "",
    '# Pass/Fail label',
    'result = "Pass" if score >= 50 else "Fail"',
    'print("Result:", result)',
    "",
    '# Default value when variable might be empty',
    'display_name = username if username else "Guest"',
    'print("User:", display_name)',
    "",
    '# Absolute value (without abs())',
    "x = -42",
    'absolute = x if x >= 0 else -x',
    'print("Absolute:", absolute)',
    "",
    '# Show a list or a placeholder',
    'cart_display = items if items else ["(empty cart)"]',
    'print("Cart:", cart_display)',
)))

# ── CELL 16 ── Section 6: Truthy/Falsy ───────────────────────────────────────
cells.append(md(L(
    "---",
    "## 6. Truthy and Falsy Values",
    "",
    "In Python, **every value** can be evaluated as `True` or `False` in a condition.",
    "You don't always need `== True` or `== False`.",
    "",
    "**Values that are Falsy (evaluate to False):**",
    "",
    "| Value | Type | Falsy because |",
    "|-------|------|--------------|",
    "| `False` | bool | It IS False |",
    "| `0` | int | Zero |",
    "| `0.0` | float | Zero |",
    "| `''` | str | Empty string |",
    "| `[]` | list | Empty list |",
    "| `{}` | dict | Empty dict |",
    "| `()` | tuple | Empty tuple |",
    "| `set()` | set | Empty set |",
    "| `None` | NoneType | Absence of value |",
    "",
    "**Everything else is Truthy** — non-zero numbers, non-empty strings, non-empty collections.",
    "",
    "> **Tip:** Use truthiness directly. Write `if name:` instead of `if name != '':` —",
    "> it's more Pythonic and handles `None` and empty strings in one check.",
)))

cells.append(code(L(
    "# See exactly which values are Falsy",
    "test_values = [",
    "    False, 0, 0.0, '', [], {}, (), set(), None,   # all Falsy",
    "    True, 1, -1, 3.14, 'hello', [0], {'a':1}, (1,)  # all Truthy",
    "]",
    "",
    'print(f"{'Value':<15} {'bool()':<8} Truthy?")',
    'print("-" * 35)',
    "for v in test_values:",
    '    truthiness = "Truthy" if v else "Falsy"',
    '    print(f"{str(v):<15} {str(bool(v)):<8} {truthiness}")',
)))

cells.append(code(L(
    "# Practical: guard against empty/None inputs",
    "def greet(name):",
    "    if not name:",   # catches None, '', 0 — all 'empty' inputs
    '        return "Hello, Guest!"',
    '    return f"Hello, {name}!"',
    "",
    'print(greet("Alice"))',
    'print(greet(""))',
    'print(greet(None))',
    "",
    "# Practical: check if a list has items before processing",
    "orders = [101, 102, 103]",
    "if orders:",
    '    print(f"Processing {len(orders)} orders: {orders}")',
    "else:",
    '    print("No orders to process.")',
)))

# ── CELL 19 ── Section 7: Comparison operators ───────────────────────────────
cells.append(md(L(
    "---",
    "## 7. Comparison Operators",
    "",
    "Comparison operators always return `True` or `False`.",
    "",
    "| Operator | Meaning | Example | Result |",
    "|----------|---------|---------|--------|",
    "| `==` | Equal to | `5 == 5` | `True` |",
    "| `!=` | Not equal to | `5 != 3` | `True` |",
    "| `<` | Less than | `3 < 5` | `True` |",
    "| `>` | Greater than | `5 > 3` | `True` |",
    "| `<=` | Less than or equal | `5 <= 5` | `True` |",
    "| `>=` | Greater than or equal | `6 >= 5` | `True` |",
    "| `in` | Membership test | `'a' in 'cat'` | `True` |",
    "| `not in` | Not a member | `4 not in [1,2,3]` | `True` |",
    "| `is` | Identity (same object) | `x is None` | depends |",
    "| `is not` | Not same object | `x is not None` | depends |",
    "",
    "**`==` vs `is`:**",
    "- `==` checks if two values are **equal**",
    "- `is` checks if two variables point to the **same object in memory**",
    "- Always use `==` for value comparison; use `is` only for `None`, `True`, `False`",
)))

cells.append(code(L(
    "# Comparison operators in action",
    "x, y = 10, 20",
    "",
    'print("== :", x == y)    # False',
    'print("!= :", x != y)    # True',
    'print("<  :", x < y)     # True',
    'print(">  :", x > y)     # False',
    'print("<= :", x <= 10)   # True',
    'print(">= :", y >= 20)   # True',
    "",
    "# Chained comparisons — very Pythonic",
    "age = 25",
    "if 18 <= age <= 65:",
    '    print(f"Age {age} is in the working-age range (18–65)")',
    "",
    "# Membership tests",
    "vowels = ['a', 'e', 'i', 'o', 'u']",
    "letter = 'e'",
    'print(f"Is \'{letter}\' a vowel?", letter in vowels)',
    "",
    "# in works on strings too",
    "sentence = 'The quick brown fox'",
    'print("Has \'quick\'?", "quick" in sentence)',
)))

cells.append(code(L(
    "# == vs is — critical distinction",
    "",
    "# Lists: same content, different objects",
    "a = [1, 2, 3]",
    "b = [1, 2, 3]",
    'print("a == b :", a == b)    # True  — same content',
    'print("a is b :", a is b)    # False — different objects in memory',
    "",
    "# None check — always use 'is', not '=='",
    "result = None",
    'print("\\nNone checks:")',
    "if result is None:",
    '    print("  result is None — correct way")',
    "",
    "# Small integers are cached — 'is' can mislead",
    "p = 256",
    "q = 256",
    'print(f"\\n256 is 256: {p is q}   # True (CPython caches -5 to 256)")',
    "p = 1000",
    "q = 1000",
    'print(f"1000 is 1000: {p is q}  # False (not cached — different objects)")',
    'print("Lesson: use == for values, is only for None/True/False")',
)))

# ── CELL 22 ── Section 8: Logical operators ──────────────────────────────────
cells.append(md(L(
    "---",
    "## 8. Logical Operators — Combining Conditions",
    "",
    "| Operator | Meaning | Result |",
    "|----------|---------|--------|",
    "| `and` | Both conditions must be True | `True and True → True` |",
    "| `or` | At least one must be True | `False or True → True` |",
    "| `not` | Inverts the condition | `not True → False` |",
    "",
    "**Truth tables:**",
    "",
    "| A | B | A and B | A or B |",
    "|---|---|---------|--------|",
    "| True | True | True | True |",
    "| True | False | False | True |",
    "| False | True | False | True |",
    "| False | False | False | False |",
    "",
    "**Precedence** (highest to lowest): `not` → `and` → `or`",
    "Use parentheses to make complex conditions explicit.",
)))

cells.append(code(L(
    "# and, or, not examples",
    "age      = 22",
    "has_id   = True",
    "is_vip   = False",
    "",
    "# and — both must be True",
    "if age >= 18 and has_id:",
    '    print("Entry allowed")',
    "",
    "# or — at least one True",
    "if is_vip or age >= 21:",
    '    print("VIP lounge or over-21 lounge access")',
    "",
    "# not — invert",
    "is_banned = False",
    "if not is_banned:",
    '    print("User is not banned")',
    "",
    "# Combining — use parentheses for clarity",
    "if (age >= 18 and has_id) or is_vip:",
    '    print("Allowed via normal OR VIP route")',
)))

cells.append(code(L(
    "# Logical operators with non-boolean values",
    "# 'and' returns the first Falsy value, or the last value if all are Truthy",
    "# 'or'  returns the first Truthy value, or the last value if all are Falsy",
    "",
    'print(0 and "hello")      # 0   (first Falsy)',
    'print(1 and "hello")      # hello (all Truthy → last value)',
    'print("" or "default")   # default (first Truthy)',
    'print("Alice" or "Bob")  # Alice (first Truthy)',
    "",
    "# Practical: provide a default when a value might be empty",
    "user_input = ''",
    'name = user_input or "Anonymous"',
    'print("Name:", name)   # Anonymous',
    "",
    "config_timeout = None",
    "timeout = config_timeout or 30",
    'print("Timeout:", timeout)   # 30',
)))

# ── CELL 25 ── Section 9: Short-circuit ──────────────────────────────────────
cells.append(md(L(
    "---",
    "## 9. Short-Circuit Evaluation",
    "",
    "Python **stops evaluating** a logical expression as soon as the outcome is determined:",
    "",
    "- `and`: if the **left** side is **False**, the right side is never evaluated",
    "  (False AND anything = False)",
    "- `or`: if the **left** side is **True**, the right side is never evaluated",
    "  (True OR anything = True)",
    "",
    "**Why it matters:**",
    "1. **Performance** — skip expensive operations when not needed",
    "2. **Safety** — avoid errors (e.g., check if a list is non-empty before indexing it)",
    "",
    "```python",
    "# Safe: the right side only runs if items is non-empty",
    "if items and items[0] == 'apple':",
    "    ...",
    "",
    "# Unsafe without short-circuit — would crash on empty list:",
    "# if items[0] == 'apple':   ← IndexError if items is []",
    "```",
)))

cells.append(code(L(
    "# Demonstrating short-circuit — the function shows when it's called",
    "",
    "def expensive_check():",
    '    print("  [expensive_check] was called")',
    "    return True",
    "",
    'print("--- and short-circuit ---")',
    'print("Left=False, right side skipped:")',
    "result = False and expensive_check()   # expensive_check NOT called",
    'print("result:", result)',
    "",
    'print("\\nLeft=True, right side evaluated:")',
    "result = True and expensive_check()    # expensive_check IS called",
    'print("result:", result)',
    "",
    'print("\\n--- or short-circuit ---")',
    'print("Left=True, right side skipped:")',
    "result = True or expensive_check()     # expensive_check NOT called",
    'print("result:", result)',
)))

cells.append(code(L(
    "# Practical short-circuit: safe list indexing",
    "orders = []",
    "",
    "# Safe — if orders is empty, orders[0] is never evaluated",
    "if orders and orders[0] == 'PRIORITY':",
    '    print("First order is priority")',
    "else:",
    '    print("No orders or first order is not priority")',
    "",
    "# Safe dictionary lookup",
    "user = {'name': 'Alice', 'role': 'admin'}",
    "",
    "# Check key exists before accessing nested value",
    "if 'role' in user and user['role'] == 'admin':",
    '    print(f"{user[\'name\']} has admin access")',
)))

# ── CELL 28 ── Section 10: Guard clauses ─────────────────────────────────────
cells.append(md(L(
    "---",
    "## 10. Guard Clauses — Flatter, Cleaner Code",
    "",
    "A **guard clause** (also called an *early return* or *early exit*) checks failure",
    "conditions **first** and returns/exits immediately, keeping the happy path at the",
    "left margin without deep nesting.",
    "",
    "**Before (nested — hard to read):**",
    "```python",
    "def process_order(user, cart, stock):",
    "    if user.is_logged_in:",
    "        if cart.total > 0:",
    "            if stock.available:",
    "                # actual logic is buried 3 levels deep",
    "                return confirm_order()",
    "            else:",
    "                return 'out of stock'",
    "        else:",
    "            return 'empty cart'",
    "    else:",
    "        return 'not logged in'",
    "```",
    "",
    "**After (guard clauses — easy to read):**",
    "```python",
    "def process_order(user, cart, stock):",
    "    if not user.is_logged_in:",
    "        return 'not logged in'",
    "    if cart.total == 0:",
    "        return 'empty cart'",
    "    if not stock.available:",
    "        return 'out of stock'",
    "    # happy path — no nesting",
    "    return confirm_order()",
    "```",
)))

cells.append(code(L(
    "# Guard clause example: validate a username",
    "",
    "def validate_username(username):",
    '    """Return (True, "") if valid, or (False, reason) if not."""',
    "    if not username:",
    '        return False, "Username cannot be empty"',
    "    if len(username) < 3:",
    '        return False, "Username must be at least 3 characters"',
    "    if len(username) > 20:",
    '        return False, "Username must be 20 characters or fewer"',
    "    if not username.isalnum():",
    '        return False, "Username can only contain letters and numbers"',
    "    # All checks passed — happy path",
    '    return True, "Username is valid"',
    "",
    "# Test different inputs",
    'tests = ["", "ab", "alice_123!", "x" * 21, "Alice99"]',
    "for t in tests:",
    "    ok, msg = validate_username(t)",
    '    symbol = "✓" if ok else "✗"',
    '    print(f"  {symbol} {repr(t):<20} → {msg}")',
)))

# ── CELL 30 ── Section 11: match ─────────────────────────────────────────────
cells.append(md(L(
    "---",
    "## 11. `match` Statement — Pattern Matching (Python 3.10+)",
    "",
    "The `match` statement compares a value against a series of **patterns**.",
    "It is more powerful than a chain of `elif` — it can match structure, not just values.",
    "",
    "```python",
    "match subject:",
    "    case pattern_1:",
    "        ...",
    "    case pattern_2 | pattern_3:   # OR patterns",
    "        ...",
    "    case _:                        # wildcard — matches anything",
    "        ...",
    "```",
    "",
    "**When to prefer `match` over `elif`:**",
    "- Matching a single variable against many exact values",
    "- Matching tuples or data structures (structural pattern matching)",
    "- The intent is 'switch/case' style dispatch",
    "",
    "> **Note:** `match` requires Python 3.10+. Check with `import sys; print(sys.version)`.",
)))

cells.append(code(L(
    "import sys",
    'print("Python version:", sys.version)',
    "",
    "# Basic match on a string value",
    "day = 'Wednesday'",
    "",
    "match day:",
    '    case "Saturday" | "Sunday":',
    '        day_type = "Weekend"',
    '    case "Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday":',
    '        day_type = "Weekday"',
    "    case _:",
    '        day_type = "Unknown"',
    "",
    'print(f"{day} is a {day_type}")',
)))

cells.append(code(L(
    "# match on HTTP status codes — cleaner than many elifs",
    "def describe_status(code):",
    "    match code:",
    "        case 200:",
    '            return "OK — request succeeded"',
    "        case 201:",
    '            return "Created — resource created successfully"',
    "        case 400:",
    '            return "Bad Request — check your input"',
    "        case 401:",
    '            return "Unauthorised — authentication required"',
    "        case 403:",
    '            return "Forbidden — you don\'t have permission"',
    "        case 404:",
    '            return "Not Found — resource does not exist"',
    "        case 500:",
    '            return "Internal Server Error — something went wrong server-side"',
    "        case _:",
    '            return f"Unrecognised status code: {code}"',
    "",
    "for status in [200, 201, 404, 403, 418]:",
    '    print(f"  {status}: {describe_status(status)}")',
)))

cells.append(code(L(
    "# Structural pattern matching — match on tuple shape",
    "def describe_point(point):",
    "    match point:",
    "        case (0, 0):",
    '            return "Origin"',
    "        case (x, 0):",
    '            return f"On the X-axis at x={x}"',
    "        case (0, y):",
    '            return f"On the Y-axis at y={y}"',
    "        case (x, y):",
    '            return f"Point at ({x}, {y})"',
    "",
    "points = [(0,0), (3,0), (0,-2), (4,5)]",
    "for p in points:",
    '    print(f"  {str(p):<10} → {describe_point(p)}")',
)))

# ── CELL 34 ── Section 12: Practice Challenges ───────────────────────────────
cells.append(md(L(
    "---",
    "## 12. Practice Challenges",
    "",
    "Work through each challenge yourself first, then reveal the solution cell below.",
    "Modify the solutions to deepen your understanding.",
)))

cells.append(md(L(
    "### Challenge 1 — FizzBuzz",
    "",
    "Print numbers 1 to 30. But:",
    "- For multiples of **3**, print `Fizz`",
    "- For multiples of **5**, print `Buzz`",
    "- For multiples of **both**, print `FizzBuzz`",
    "- Otherwise, print the number",
    "",
    "**Hint:** use `%` (modulo operator) to check divisibility.",
)))

cells.append(code(L(
    "# Challenge 1 Solution — FizzBuzz",
    "for n in range(1, 31):",
    "    if n % 15 == 0:",   # divisible by both 3 and 5 — check FIRST
    '        print("FizzBuzz", end="  ")',
    "    elif n % 3 == 0:",
    '        print("Fizz", end="  ")',
    "    elif n % 5 == 0:",
    '        print("Buzz", end="  ")',
    "    else:",
    "        print(n, end='  ')",
    'print()   # newline at end',
)))

cells.append(md(L(
    "### Challenge 2 — BMI Calculator",
    "",
    "Given `weight_kg` and `height_m`, calculate BMI and classify:",
    "",
    "| BMI | Category |",
    "|-----|----------|",
    "| < 18.5 | Underweight |",
    "| 18.5 – 24.9 | Normal |",
    "| 25.0 – 29.9 | Overweight |",
    "| ≥ 30.0 | Obese |",
    "",
    "`BMI = weight / height²`",
)))

cells.append(code(L(
    "# Challenge 2 Solution — BMI Calculator",
    "def bmi_category(weight_kg, height_m):",
    "    if height_m <= 0:",
    '        return "Invalid height"',
    "    bmi = weight_kg / (height_m ** 2)",
    "    if bmi < 18.5:",
    '        category = "Underweight"',
    "    elif bmi < 25.0:",
    '        category = "Normal"',
    "    elif bmi < 30.0:",
    '        category = "Overweight"',
    "    else:",
    '        category = "Obese"',
    '    return f"BMI = {bmi:.1f} ({category})"',
    "",
    "# Test cases",
    'print(bmi_category(50,  1.70))   # Underweight',
    'print(bmi_category(70,  1.75))   # Normal',
    'print(bmi_category(90,  1.75))   # Overweight',
    'print(bmi_category(110, 1.75))   # Obese',
)))

cells.append(md(L(
    "### Challenge 3 — Leap Year Checker",
    "",
    "A year is a leap year if:",
    "- Divisible by **4**, AND",
    "- If divisible by **100**, it must also be divisible by **400**",
    "",
    "Examples: 2000 ✓, 1900 ✗, 2024 ✓, 2023 ✗",
)))

cells.append(code(L(
    "# Challenge 3 Solution — Leap Year Checker",
    "def is_leap_year(year):",
    "    if year % 400 == 0:",
    "        return True",
    "    if year % 100 == 0:",
    "        return False",
    "    return year % 4 == 0",
    "",
    "# Or as a single expression:",
    "# return (year % 4 == 0) and (year % 100 != 0 or year % 400 == 0)",
    "",
    "test_years = [2000, 1900, 2024, 2023, 1600, 1700]",
    "for y in test_years:",
    '    result = "Leap year ✓" if is_leap_year(y) else "Not a leap year ✗"',
    '    print(f"  {y}: {result}")',
)))

cells.append(md(L(
    "### Challenge 4 — Password Strength Checker",
    "",
    "Write a function `check_password(pwd)` that rates a password:",
    "",
    "| Condition | Points |",
    "|-----------|--------|",
    "| Length ≥ 8 | +1 |",
    "| Contains a digit | +1 |",
    "| Contains uppercase letter | +1 |",
    "| Contains lowercase letter | +1 |",
    "| Contains special character (`!@#$%`) | +1 |",
    "",
    "Score 5 = Strong, 3–4 = Medium, < 3 = Weak",
)))

cells.append(code(L(
    "# Challenge 4 Solution — Password Strength Checker",
    "def check_password(pwd):",
    "    score = 0",
    '    SPECIAL = set("!@#$%^&*()")',
    "",
    "    if len(pwd) >= 8:                          score += 1",
    "    if any(c.isdigit() for c in pwd):          score += 1",
    "    if any(c.isupper() for c in pwd):          score += 1",
    "    if any(c.islower() for c in pwd):          score += 1",
    "    if any(c in SPECIAL for c in pwd):         score += 1",
    "",
    "    if score == 5:",
    '        strength = "Strong   💪"',
    "    elif score >= 3:",
    '        strength = "Medium   ⚠️"',
    "    else:",
    '        strength = "Weak     ❌"',
    "",
    '    return f"Score {score}/5 — {strength}"',
    "",
    'passwords = ["abc", "password", "P@ssw0rd!", "hello123", "ALLCAPS1!"]',
    "for p in passwords:",
    '    print(f"  {p:<20} → {check_password(p)}")',
)))

cells.append(md(L(
    "### Challenge 5 — Simple ATM Simulator",
    "",
    "Simulate a mini ATM with a fixed balance:",
    "- If withdrawal amount > 0 and <= balance: approve it",
    "- If amount > balance: decline (insufficient funds)",
    "- If amount <= 0: reject (invalid amount)",
    "- After withdrawal, print the new balance",
)))

cells.append(code(L(
    "# Challenge 5 Solution — ATM Simulator",
    "def atm_withdraw(balance, amount):",
    '    """Process a withdrawal. Returns (new_balance, message)."""',
    "    if amount <= 0:",
    '        return balance, f"Invalid amount: £{amount:.2f}. Enter a positive number."',
    "    if amount > balance:",
    '        return balance, f"Insufficient funds. Balance: £{balance:.2f}, Requested: £{amount:.2f}"',
    "    new_balance = balance - amount",
    '    return new_balance, f"Dispensing £{amount:.2f}. New balance: £{new_balance:.2f}"',
    "",
    "balance = 500.00",
    'print(f"Starting balance: £{balance:.2f}\\n")',
    "",
    "transactions = [200.00, 350.00, -50.00, 0, 50.00]",
    "for amount in transactions:",
    "    balance, msg = atm_withdraw(balance, amount)",
    '    print(f"  Withdraw £{amount:.2f:>8} → {msg}")',
)))

# ── CELL 46 ── Key Takeaways ──────────────────────────────────────────────────
cells.append(md(L(
    "---",
    "## Key Takeaways",
    "",
    "| Concept | What to remember |",
    "|---------|-----------------|",
    "| `if` | Runs a block when condition is True |",
    "| `elif` | Only checked if all previous conditions were False |",
    "| `else` | Catches everything — no condition |",
    "| Ternary | `x if cond else y` — one-liner for simple assignments |",
    "| Falsy | `0, '', [], {}, None, False` all behave as False |",
    "| `==` vs `is` | `==` compares values; `is` compares object identity |",
    "| `and` | Both must be True; stops at first False (short-circuit) |",
    "| `or` | One must be True; stops at first True (short-circuit) |",
    "| Guard clauses | Check failures first, return early, keep happy path flat |",
    "| `match` | Pattern matching (Python 3.10+); cleaner than many `elif`s |",
    "",
    "### Common Mistakes to Avoid",
    "1. **`=` vs `==`**: `if x = 5` is a syntax error; use `if x == 5`",
    "2. **Forgetting the colon**: `if x > 0` → must be `if x > 0:`",
    "3. **Wrong indentation**: Python uses indentation to define blocks — be consistent",
    "4. **Using `is` for value comparison**: `if x is 5` — use `if x == 5`",
    "5. **Checking FizzBuzz wrong order**: check `% 15` before `% 3` and `% 5`",
    "6. **Deep nesting**: if you need more than 2 levels, consider guard clauses",
)))

nb = {
    "nbformat": 4,
    "nbformat_minor": 4,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.10.0"},
    },
    "cells": cells,
}

OUT = r"c:\Users\PS\Documents\Python-Exp\Python-Notebooks\05-Conditionals.ipynb"
with open(OUT, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

# Validate
with open(OUT, encoding="utf-8") as f:
    check = json.load(f)
assert len(check["cells"]) == len(cells), f"Expected {len(cells)}, got {len(check['cells'])}"
print(f"Done: {len(cells)} cells, valid=True")
print(f"Written to: {OUT}")
